try
  Test()
catch (ex:Exception)
  println ex
endTry

routine Test
  println "A"
  throw UnsupportedOperationError( "B" )
  println "C"
endRoutine
